WEEK05/myinsta/urls.py
from django.contrib import admin
from django.urls import path, include

from posts.views import url_view, url_parameter_view, function_view, index
from posts.views import class_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<int:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()), 

    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),
]

WEEK05/posts/urls.py
from django.urls import path

from .views import post_diary_view
from .views import post_sns_view, post_song_view, post_photo_view

app_name='posts'

urlpatterns=[
    path('', post_diary_view, name='post-diary'),
    path('<int:id>/', post_song_view),
    path('<int:id>/photo', post_photo_view),
    path('<int:id>/sns', post_sns_view),
]

WEEK05/posts/models.py
from django.db import models

# Create your models here.

class Post (models.Model):

    image =models.ImageField(verbose_name='이미지')
    contents = models.TextField('내용')
    created_at=models.DateTimeField('작성일')
    view_count=models.IntegerField('조회수')

WEEK05/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from django.views.generic import ListView
from .models import Post

# Create your views here.

def index(request):
    return render(request, 'index.html')

def post_diary_view(request):
    return render(request, 'posts/post_diary.html')

def post_song_view(request):
    return render(request, 'posts/post_song.html')

def post_photo_view(request, id):
    return render(request, 'posts/post_photo.html')

def post_sns_view(request, id):
    return render(request, 'posts/post_sns.html')
#CBV
class class_view(ListView):
    model = Post
    template_name='cbv_view.html'

#FBV
def url_view(request):
    data ={'code': '001', 'msg':'OK'}
    return HttpResponse('<h1>url_views</h1>')

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method: {request.method}')
    print(f'request.GET: {request.GET}')
    print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

WEEK05/myinsta/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} Page | 지효그램</title>
</head>
<body>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

WEEK05/myinsta/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="deco.css">
    <title>Index Page | 지효그램</title>
</head>
<body>
    <h1>자기소개 화면</h1>
    <p>안녕하세요! 반갑습니다^^</p>
    <ul>
        <li><a href="{% url 'posts:post-diary' %}">오늘의 일기</a></li>
       
    </ul>
</body>
</html>

WEEK05/myinsta/templates/posts/post_diary.html

{% extends 'base.html' %}
{% block title %}Diary{% endblock %}

{% block content %}
<h1>오늘의 일기장!</h1>
{% endblock %}

WEEK05/myinsta/templates/posts/post_photo.html

{% extends 'base.html' %}
{% block title %}Photo{% endblock %}

{% block content %}
<h1>사진모음집</h1>
{% endblock %}

WEEK05/myinsta/templates/posts/post_sns.html


{% extends 'base.html' %}
{% block title %}SNS{% endblock %}

{% block content %}
<h1>SNS 링크 정리</h1>
{% endblock %}

WEEK05/myinsta/templates/posts/post_song.html


{% extends 'base.html' %}
{% block title %}Song{% endblock %}

{% block content %}
<h1>노래추천 모음</h1>
{% endblock %}

WEEK05/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        <li>{{ object.title }}</li>
    {% endfor %}
</body>
</html>

WEEK05/posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href = "/fbv/">새로고침</a>

    <form action="" method="'get">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>

    <form action="" method="post">
        <input type="text" name="var"> {% csrf_token %}
        <input type="submit" value="POST 제출">
    </form>
</body>
</html>